### ISSUE TITLE
Depend on newer version of setuptools

### ISSUE THREAD

**Issue by h4writer** [mozilla-services/pulseguardian#17]
I was trying to install pulseguardian, but failed miserable. Always getting errors when installing the dependencies:

error in setup command: Error parsing /home/h4writer/Build/pulse_actions/build/mock/setup.cfg: SyntaxError: '<' operator not allowed in environment markers

After searching I found out I needed to upgrade my setuptools:
http://docs.openstack.org/developer/pbr/compatibility.html#evaluate-marker

To make it easier for other, should it depend on "setuptools  >= 17.1"

**Comment by markrcote** [comment]
Sorry I missed this (we tend to use bugzilla.mozilla.org for bugs).  I pinned the version to 36.0.1.
