### ISSUE TITLE
The Queues page hides most entries after a few seconds

### ISSUE THREAD

**Issue by edmorley** [mozilla-services/pulseguardian#39]
**STR:**
1. Log in as an admin
2. Visit https://pulseguardian.mozilla.org/queues

**Expected:**
Either all queues are displayed (and remain displayed) on one page, or else a subset of them are displayed with a way to see the rest (eg pagination).

**Actual:**
On initial pageload hundreds of queues are visible (watch the size of the scrollbar to get an impression of the quantity), but after a few seconds most of them disappear, being replaced with just a "Queues with unknown owners" heading and 5 or so queues,

**Comment by markrcote** [comment]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1362106. I started work on this before the break. I'm going to try to make a bit of time to finish it.

**Comment by edmorley** [comment]
Fixed by:
https://github.com/mozilla-services/pulseguardian/commit/5e1f1a59d60845338aa6b47044ad80731cc97d6c
https://github.com/mozilla-services/pulseguardian/commit/25576a7aa3436d2bd31cc1fc2fbb55e8b92d6a9f
