### ISSUE TITLE
If queues are unbounded, email notice of growing queues should not mention "deletion"

### ISSUE THREAD

**Issue by sarah-clements** [mozilla-services/pulseguardian#411]
I got this email recently, but it caused confusion about whether or not the unbounded queues would actually be deleted or not once it hits the limit:

Warning: your queue "queue/that-does-thing" on exchange "could not be determined" is
overgrowing (4015 ready messages, 4015 total messages).

The queue will be automatically deleted when it exceeds 20000 messages.

Make sure your clients are running correctly and are cleaning up unused
durable queues.

Check messages in the queue at: https://pulseguardian.mozilla.org/queues

**Comment by djmitche** [comment]
It tries to determine the exchange for a queue by looking at the `incoming` property of the queue from the management API.  This is described in [the docs](https://rawcdn.githack.com/rabbitmq/rabbitmq-server/v3.8.14/deps/rabbitmq_management/priv/www/api/index.html) as " Detailed message stats (see section above) for publishes from exchanges into this queue." but appears to be empty for the queues that I've looked at.  Maybe this is an old RabbitMQ feature?  At any rate, in practice lots of queues are bound to many exchanges, so I don't think this is a useful piece of information to include in the email.  I'll make a PR to just remove it.

**Comment by djmitche** [comment]
^^ that relates to bug 1403343, not to this issue.  But I'll fix 'em both in the same PR.

**Comment by djmitche** [comment]
```
Warning: your queue "queue/dustin/testing-deleteme" is overgrowing (5314 ready messages,
5314 total messages).

This queue is unbounded and will not be automatically deleted.

Make sure your clients are running correctly and are cleaning up unused
durable queues.

Check messages in the queue at: https://pulseguardian.mozilla.org/queues
```

**Comment by sarah-clements** [comment]
Much clearer - thanks!
