### ISSUE TITLE
Unable to sign in to pulseguardian

### ISSUE THREAD

**Issue by Biboswan** [mozilla-services/pulseguardian#74]
![unlogin](https://user-images.githubusercontent.com/22202556/37910102-534c5174-312a-11e8-91ed-534df71784d6.png)

I 'm able to auto log into tools.taskcluster.net and mozillians.org as well. But on trying to sign in to pulse guardian I get this. I tried in private browser window and ultimately got the same error.

Note: I 'm vouched (as I think that is needed to have authorization rights to use pulse guardian) and my github account is linked too.

**Comment by markrcote** [comment]
Could you try this again? I wonder if some recent changes to auth may have fixed this.

**Comment by Biboswan** [comment]
Yeah it worked. Thanks
